[build]
  command = "CI=false npm install && npm run build"
  publish = "build" # For Create React App
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10.8.2"
  CI = "false"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "openai", "@anthropic-ai/sdk"]
  directory = "netlify/functions"
  
  [functions.chatbot]
  timeout = "30"

[dev]
  framework = "vite"
  targetPort = 5173

# Add proper MIME type headers
[[headers]]
  for = "/assets/*.js"
[headers.values]
  Content-Type = "text/plain"

[[headers]]
  for = "/assets/*.css"
[headers.values]
  Content-Type = "text/css"

[[headers]]
  for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type"
